In [1]:
import numpy as np
a=np.array([1,2,3])
print("one dimenstional array a=",a)
b=np.array([1,2,3]),([4,5,6])
print("two dimenstional array b=",b)
print("size of the array :",a.shape)
print("element at indices 0,1,2",a[0],a[1],a[2])
a[0]=5
print("array after changing the amount at index 0:",a)
a=np.zeros((2,2))
print("an array of all zeros:",a)
b=np.ones((1,2))
print("an array of all ones:",b)
c=np.full((2,2),7)
print("a constant array :",6)
d=np.eye(2)
print("a 2*2 identify matrix:",d)
e=np.random.random((2,2))
print("an array with random values:",e)

one dimenstional array a= [1 2 3]
two dimenstional array b= (array([1, 2, 3]), [4, 5, 6])
size of the array : (3,)
element at indices 0,1,2 1 2 3
array after changing the amount at index 0: [5 2 3]
an array of all zeros: [[0. 0.]
 [0. 0.]]
an array of all ones: [[1. 1.]]
a constant array : 6
a 2*2 identify matrix: [[1. 0.]
 [0. 1.]]
an array with random values: [[0.05460424 0.0802725 ]
 [0.93080885 0.25277294]]


In [2]:
import numpy as np
print("array indexing:slicing")
a1=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("a1=",a1)


array indexing:slicing
a1= [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [3]:
b=a1[:2,1:3]
print("subarray consisting of first two rows and columns 1 and 2:",b)

subarray consisting of first two rows and columns 1 and 2: [[2 3]
 [6 7]]


In [4]:
b=a1[1:2,:]
print("subarray consists of second row:",b)
print("accessing columns:")
b=a1[:,1]
print(b,b.shape)

subarray consists of second row: [[5 6 7 8]]
accessing columns:
[ 2  6 10] (3,)


In [6]:
c=a1[:,1:2]
print(c,c.shape)
print("array integer indexing:")
a2=np.array([[1,2],[3,4],[5,6]])
print("a2=",a2)
print("example of array integer indexing:",a2[[0,1,2],[0,1,0]])
print(a2[[0,0],[1,1]])
print(np.array([a2[0,1],a1[0,1]]))

[[ 2]
 [ 6]
 [10]] (3, 1)
array integer indexing:
a2= [[1 2]
 [3 4]
 [5 6]]
example of array integer indexing: [1 4 5]
[2 2]
[2 2]


In [10]:
a3=a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print("a3=",a3)
b=konp.array([0,2,0,1])
print("b=",b)
print("a3=",a3[np.arange(4),b])
a3[np.arange(4),b]
print("a3=",a3)
print("boolean array indexing:")
a=np.array([[1,2],[3,4],[5,6]])
print("a=",a)
bool_idx=(a>2)
print("elements greater than 2:",a[bool_idx])

a3= [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
b= [0 2 0 1]
a3= [ 1  6  7 11]
a3= [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
boolean array indexing:
a= [[1 2]
 [3 4]
 [5 6]]
elements greater than 2: [3 4 5 6]


In [15]:
import numpy as n 
x=np.array([[1,2],[3,4]],dtype=np.float64)
y=np.array([[6,9],[4,4]],dtype=np.float64)
print("x=",x)
print("y=",y)
print("element wise addition:",np.add(x,x))
print("element wise subtract:",np.subtract(x,y))
print("element wise multiplication:",np.multiply(x,y))
print("element wise square root of x:",np.sqrt(x))
print("matrix multiplication:",np.dot(x,y))
print("sum of all element of matrix x:",np.sum(x))
print("sum of elements in each column of matrix y:",np.sum(y,axis=0))
print("sum of elements in each row of matrix y:",np.sum(y,axis=1))
print("Transpose of matrix x:",x.T)

x= [[1. 2.]
 [3. 4.]]
y= [[6. 9.]
 [4. 4.]]
element wise addition: [[2. 4.]
 [6. 8.]]
element wise subtract: [[-5. -7.]
 [-1.  0.]]
element wise multiplication: [[ 6. 18.]
 [12. 16.]]
element wise square root of x: [[1.         1.41421356]
 [1.73205081 2.        ]]
matrix multiplication: [[14. 17.]
 [34. 43.]]
sum of all element of matrix x: 10.0
sum of elements in each column of matrix y: [10. 13.]
sum of elements in each row of matrix y: [15.  8.]
Transpose of matrix x: [[1. 3.]
 [2. 4.]]
