In [2]:
import numpy as np
print("Array indexing: slicing")
al = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("al = ", al)
b = al[:2, 1:3]
print("Subarray consisting of first two rows and columns 1 and 2: ", b)
b = al[1:2, :]
print("Subarray consisting of second row: ", b)
print("Accessing columns: ")
b = al[:, 1]
print(b, b.shape)
c = al[:, 1:2]
print(c, c.shape)
print("Array integer indexing: ")
a2 = np.array([[1, 2], [3, 4], [5, 6]])
print("a2 = ", a2)
print("Example of array integer indexing: ", a2[[0, 1, 2], [0, 1, 0]])
print("Equivalent to the previous integer array indexing example: ", a2[[0, 0], [1, 1]])
print(np.array([a2[0, 1], a2[0, 1]]))
print("Array of indices example: ")
a3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print("a3 = ", a3)
b = np.array([0, 2, 0, 1])
print("b = ", b)
print("a3 = ", a3[np.arange(4), b])
a3[np.arange(4), b] += 10
print("a3 after mutation = ", a3)
print("Boolean array indexing: ")
a = np.array([[1, 2], [3, 4], [5, 6]])
print("a = ", a)
bool_idx = (a > 2)
print("Elements greater than 2: ", a[bool_idx])


Array indexing: slicing
al =  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Subarray consisting of first two rows and columns 1 and 2:  [[2 3]
 [6 7]]
Subarray consisting of second row:  [[5 6 7 8]]
Accessing columns: 
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)
Array integer indexing: 
a2 =  [[1 2]
 [3 4]
 [5 6]]
Example of array integer indexing:  [1 4 5]
Equivalent to the previous integer array indexing example:  [2 2]
[2 2]
Array of indices example: 
a3 =  [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
b =  [0 2 0 1]
a3 =  [ 1  6  7 11]
a3 after mutation =  [[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]
Boolean array indexing: 
a =  [[1 2]
 [3 4]
 [5 6]]
Elements greater than 2:  [3 4 5 6]


In [ ]:
import numpy as np  # Corrected import statement
x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[6, 9], [4, 4]], dtype=np.float64)
print("x = ", x)
print("y = ", y)  # Fixed the period to a comma
print("Element-wise addition of x and y: ", np.add(x, y))  # Fixed to add x and y
print("Element-wise subtraction of x and y: ", np.subtract(x, y))
print("Element-wise multiplication of x and y: ", np.multiply(x, y))
print("Element-wise square root of x: ", np.sqrt(x))
print("Matrix multiplication of x and y: ", np.dot(x, y))
print("Sum of all elements of matrix x: ", np.sum(x))
print("Sum of elements in each column of matrix y: ", np.sum(y, axis=0))
print("Sum of elements in each row of matrix y: ", np.sum(y, axis=1))
print("Transpose of matrix x: ", x.T)
